name: Master Workflow

on:
  push:
    branches: [ master ]

jobs:
  runner-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Create bootjar
        run: ./gradlew :app:bootJar
