name: PR Workflow

on:
  pull_request:
    branches: [ dev ]

jobs:
  runner-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run tests
        run: ./gradlew --build-cache :app:test :module-a:test :module-b:test
